# Generated by Django 3.0.6 on 2020-05-13 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='year_of_start',
        ),
    ]
