# Generated by Django 3.0.6 on 2020-05-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='year_of_start',
            field=models.IntegerField(),
        ),
    ]
